/* Generated By:JavaCC: Do not edit this line. LolParserVisitor.java Version 5.0 */
package lolparser.frontend;

public interface LolParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=60e3df17f6d4a7d37691591021541eda (do not edit this line) */
