/* Generated By:JavaCC: Do not edit this line. LolParserTreeConstants.java Version 5.0 */
package lolparser.frontend;

public interface LolParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTVOID = 1;
  public int JJTASSIGNMENTEXPRESSION = 2;
  public int JJTVARDECLAREEXPRESSION = 3;
  public int JJTSUM = 4;
  public int JJTDIFF = 5;
  public int JJTPRODUKT = 6;
  public int JJTQUOSHUNT = 7;
  public int JJTMOD = 8;
  public int JJTBIGGR = 9;
  public int JJTSMALLR = 10;
  public int JJTUP = 11;
  public int JJTBOOLEANOPERATION = 12;
  public int JJTBOTH = 13;
  public int JJTEITHER = 14;
  public int JJTWON = 15;
  public int JJTNOT = 16;
  public int JJTCOMPARISIONOPERATION = 17;
  public int JJTBOTHSAEM = 18;
  public int JJTDIFFRINT = 19;
  public int JJTLOOP = 20;
  public int JJTIFTHEN = 21;


  public String[] jjtNodeName = {
    "parse",
    "void",
    "AssignmentExpression",
    "VarDeclareExpression",
    "SUM",
    "DIFF",
    "PRODUKT",
    "QUOSHUNT",
    "MOD",
    "BIGGR",
    "SMALLR",
    "UP",
    "BooleanOperation",
    "BOTH",
    "EITHER",
    "WON",
    "NOT",
    "ComparisionOperation",
    "BOTHSAEM",
    "DIFFRINT",
    "loop",
    "ifThen",
  };
}
/* JavaCC - OriginalChecksum=2b155c510ab0922437351f6aa4582e7a (do not edit this line) */
