HAI

I HAS A ANIMAL
ANIMAL R "RABBIT"
VISIBLE ANIMAL
BOTH SAEM ANIMAL AN "CAT"
O RLY?
  YA RLY
  VISIBLE "J00 HAV A CAT"
  MEBBE BOTH SAEM ANIMAL AN "MAUS"
    VISIBLE "NOM NOM NOM. I EATED IT."
  MEBBE BOTH SAEM ANIMAL AN "DOG"
	VISIBLE "WHHYYYY would you have a dog in a LOL program?"
  NO WAI
	VISIBLE "J00 SUX"
OIC
VISIBLE "K BAI"
KTHXBYE